version: "3.9"

services:
  backend:
    image: review-insight/back
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app/src
      - ALLOWED_ORIGINS=http://localhost:8080
      - LOG_LEVEL=info
    volumes:
      - ./apps/backend/src:/app/src
      - ./apps/backend/tests:/app/tests
    ports:
      - "8000:8000"
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: review-insight/front:latest
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "8080:8080"
    volumes:
      - ./apps/frontend/src:/app/src
      - ./apps/frontend/index.html:/app/index.html
      - ./apps/frontend/vite.config.ts:/app/vite.config.ts
      - ./apps/frontend/vite.config.server.ts:/app/vite.config.server.ts
      - ./apps/frontend/tsconfig.json:/app/tsconfig.json
      - ./apps/frontend/server:/app/server
      - ./apps/frontend/public:/app/public
    command: pnpm dev --host 0.0.0.0